packages:
  - apps/*
  - packages/*
catalogs:
  lint:
    '@wisemen/eslint-config-vue': 1.1.0
    eslint: 9.32.0
    'eslint-config-next': '15.4.4'
  types:
    typescript: 5.8.3
    zod: 3.25.76
    '@types/dom-view-transitions': 1.0.6
    '@types/body-scroll-lock': '3.1.2'
    '@types/node': '22.16.5'
    '@types/react': '19.1.9'
    '@types/react-dom': '19.1.7'
  test:
    vitest: 3.2.4
  payload:
    '@payloadcms/db-postgres': 3.49.0
    '@payloadcms/next': 3.49.0
    '@payloadcms/plugin-seo': 3.49.0
    '@payloadcms/richtext-lexical': 3.49.0
    '@payloadcms/storage-s3': 3.49.0
    '@payloadcms/ui': 3.49.0
    '@payloadcms/live-preview-vue': 3.49.0
    '@payloadcms/live-preview': 3.49.0
    payload: 3.49.0
    '@payloadcms/plugin-multi-tenant': 3.49.0
  orpc:
    '@orpc/server': 1.7.5
    '@orpc/contract': 1.7.5
    '@orpc/client': 1.7.5
  nuxt:
    nuxt: 4.0.2
    '@nuxt/eslint': 1.7.1
    '@nuxt/fonts': 0.11.4
    '@nuxtjs/color-mode': 3.5.2
    '@nuxtjs/i18n': 10.0.3
    '@nuxtjs/robots': 5.4.0
    '@nuxtjs/sitemap': 7.4.3
    nuxt-schema-org: 5.0.6
    vue: 3.5.18
    vue-router: 4.5.1
    '@vueuse/core': 13.6.0
    '@vueuse/nuxt': 13.6.0
    '@nuxt/devtools': 2.6.2
    '@nuxt/test-utils': 3.19.2
    '@vue/test-utils': 2.4.6
    vue-tsc: 3.0.4
    pinia: 3.0.3
    '@pinia/nuxt': 0.11.2
    '@lukemorales/query-key-factory': 1.3.4
    '@tanstack/vue-query': 5.83.0
    reka-ui: 2.4.0
    '@wisemen/vue-core-components': 1.12.0
  tailwind:
    tailwind-merge: 3.3.1
    tailwind-variants: 2.0.1
    tailwindcss: 4.1.11
    '@tailwindcss/vite': 4.1.11
    '@tailwindcss/typography': 0.5.16
  utils:
    i18n-iso-countries: 7.14.0
    libphonenumber-js: 1.12.10
    maska: 3.2.0
  auth:
    '@wisemen/vue-core-auth': 2.0.1
  form:
    formango: 3.1.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
